site_name: FastAPI Hive
site_description: FastAPI Hive Framework, modulization code layout tools, decoupling codes into cornerstones and endpoints, developer-friendly, easy to be integrated.
site_url: https://fanqingsong.github.io/fastapi-hive/what/
theme:
  name: material
repo_name: fanqingsong/fastapi-hive
repo_url: https://github.com/fanqingsong/fastapi-hive
nav:
- what.md
- why.md
- how.md
- design.md
- usecases.md
- reference.md
- model_description.md



