site_name: FastAPI Hive
site_description: FastAPI Endpoint Framework, packages&xxx_endpoint code structure, developer-friendly, easy to be integrated.
site_url: https://fanqingsong.github.io/fastapi-hive/
theme:
  name: material
repo_name: fanqingsong/fastapi-hive
repo_url: https://github.com/fanqingsong/fastapi-hive
nav:
- index.md
- why.md
- how.md
- design.md
- model_description.md



